# Step 1: Build
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /reprocessor ./cmd/beer_style_reprocessor/main.go

# Step 2: Runtime
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /reprocessor .
# COPIA O .ENV AQUI
COPY --from=builder /app/.env .

CMD ["./reprocessor"]